package yaml

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/AlexGladkov/harnest/internal/mapping"
	goyaml "gopkg.in/yaml.v3"
)

const (
	configFileName  = "harnest.yaml"
	supportedVersion = 1

	fileHeader = `# harnest.yaml — declarative configuration for the Harnest CLI.
# Generated by Harnest. Edit freely; run 'harnest generate' to apply changes.
# Documentation: https://github.com/AlexGladkov/harnest
`
)

// Load reads and parses harnest.yaml from the given directory.
// Returns an error if the file does not exist, cannot be parsed, or specifies
// an unsupported version.
func Load(dir string) (*HarnestConfig, error) {
	path := filepath.Join(dir, configFileName)

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("harnest.yaml not found in %s: run 'harnest init' to create one", dir)
		}
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}

	var cfg HarnestConfig
	if err := goyaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}

	if cfg.Version != supportedVersion {
		return nil, fmt.Errorf(
			"unsupported harnest.yaml version %d (expected %d): please upgrade the Harnest CLI",
			cfg.Version, supportedVersion,
		)
	}

	return &cfg, nil
}

// Save marshals cfg to YAML and writes it to harnest.yaml in the given directory.
// The output file is prefixed with a descriptive header comment.
func Save(dir string, cfg *HarnestConfig) error {
	if cfg == nil {
		return fmt.Errorf("cannot save nil config")
	}

	data, err := goyaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	path := filepath.Join(dir, configFileName)
	content := fileHeader + "\n" + string(data)

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	return nil
}

// Exists reports whether harnest.yaml is present in the given directory.
func Exists(dir string) bool {
	info, err := os.Stat(filepath.Join(dir, configFileName))
	return err == nil && !info.IsDir()
}

// ToAgentConfig converts a HarnestConfig into a mapping.AgentConfig that can
// be passed directly to harness generators.
func (cfg *HarnestConfig) ToAgentConfig() mapping.AgentConfig {
	ac := mapping.AgentConfig{
		Models: make(map[string]string),
	}

	// Consilium: preserve declaration order by iterating the map in a stable way.
	// We build a slice from the map so generators receive a deterministic list.
	for role, agent := range cfg.Agents.Consilium {
		ac.Consilium = append(ac.Consilium, mapping.ConsiliumRole{
			Role:  role,
			Agent: agent,
		})
	}

	// Executing agents.
	for _, e := range cfg.Agents.Executing {
		ac.Exec = append(ac.Exec, mapping.ExecAgent{
			Agent: e.Agent,
			Scope: e.Scope,
		})
	}

	// Model tiers: start from defaults, then apply overrides from config.
	defaults := mapping.DefaultModelTiers()
	for role, tier := range defaults {
		ac.Models[role] = tier
	}
	for role, tier := range cfg.Agents.Models {
		ac.Models[role] = tier
	}

	return ac
}
